name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - '**/*.ts'
      - '**/*.tsx'

jobs:
  lint:
    name: Run ESLint and Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier check
        run: yarn fmt:check
